### ISSUE TITLE
Canvas - Interação de Movimento

### ISSUE THREAD

**Issue by patrikfreisner** [patrikfreisner/canvas_gitrep#1]
Conseguir ter a interação usuário programa, para que o mesmo possa interagir com os polígonos na tela.

**Comment by JohnyKleinCatolica** [comment]
Mostrar na tela polígonos que formem um tangram

**Comment by patrikfreisner** [comment]
Verificar o uso do plugin jquery e jcanvas, para facilidade do projeto.

**Comment by patrikfreisner** [comment]
Estudando plugin hammer.js
