### ISSUE TITLE
Estudar HTML5/JavaScript Canvas

### ISSUE THREAD

**Issue by gregori** [patrikfreisner/canvas_gitrep#5]
Preparar um estudo sobre o Canvas HTML5/JS - Como "desenhar" na tela? Quais funcionalidades?

Definição de pronto: artigo escrito (pode ser em Markdown, com commit no repositório)

**Comment by JohnyKleinCatolica** [comment]
https://github.com/patrikfreisner/canvas_gitrep/wiki/HTML
