### ISSUE TITLE
Criar página inicial para a aplicação

### ISSUE THREAD

**Issue by gregori** [patrikfreisner/canvas_gitrep#6]
Criar página inicial com menu "dummy" (sem funcionalidade) e canvas

**Comment by LucasJorgeHubert** [comment]
@gregori, existe um novo arquivo de index criado, dentro de um diretório organizado para manter controle dos arquivos. segue link ( https://github.com/patrikfreisner/canvas_gitrep/blob/master/canvas_gitrep-master/index.html )

**Comment by gregori** [comment]
Eu acho que dá pra dar uma reorganizada no código, no repositório de vocês. Quarta-feira conversamos na aula, a respeito.
